config/routes.rb
Rails.application.routes.draw do

  resources(:locations, only: []) do

    collection do
      get(':country_id/states', action: :states)
      get(':state_id/cities', action: :cities)
    end

  end


  resources(:users)


  resources(:home, only: :index) do

    collection do
      get(:gmap)
      get(:get_distance)
    end

    member do
      get(:distance_from)
    end

  end

  root 'home#index'
end

app/models/user.rb
class User < ActiveRecord::Base

  geocoded_by :full_address
  validates :name, :address, :country, presence: true
  validates :city, presence: true, if: :validate_city?

  after_validation :validate_address
  after_validation :geocode

  scope :get_users, -> (ids) { where(id: ids) }

  def validate_address
    user_address = address
    user_address = "#{user_address}, #{city_name}" if city.present?
    user_address = "#{user_address}, #{state_name}" if state
    user_address = "#{user_address}, #{country_name}" if country
    self.full_address = user_address
  end


  def validate_city?
    country_code = ['VG', 'VA', 'UM', 'TC', 'SX', 'SG', 'RE', 'PW', 'PN', 'PM', 'NU', 'NF', 'MQ', 'MO', 'MH', 'MF', 'MC', 'KY', 'IO', 'IM',
                    'GS', 'GP', 'GI', 'GF', 'FM', 'FK', 'DJ', 'CX', 'CW', 'CK', 'CC', 'BL', 'AW', 'AQ', 'AI']
    !country_code.include? country
  end


  def state_name
    CS.states(country.to_sym)[state.to_sym] if state.present?
  end


  def country_name
    CS.countries[country.to_sym]
  end

  def city_name
    city.split('_').map(&:capitalize).join(' ')
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate


  def find_error(obj)
      key = obj.errors.messages.keys.first.to_s
      obj.errors.messages.stringify_keys[key].first
  end

  protected

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == "GuestUser12" && password == "Welcome1!"
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @users = User.all
    @user = @users.first
  end

  def gmap
    @user = User.find params[:id]
  end

  def get_distance
    ids = params[:ids].split(',')
    users = User.where(id: ids)
    if users.first.country == users.last.country
      render json: {
                 origin: users.first.full_address,
                 destination: users.last.full_address,
                 distance: users.first.distance_from([users.last.latitude, users.last.longitude]).round(2)
             }
    else
      render json: {error: 'Cannot get distance of two different Countries'}
    end

  end

  def distance_from
    @user = User.find params[:id]
    @users = User.all
  end

end

app/controllers/locations_controller.rb
require 'city-state'
class LocationsController < ApplicationController

  def states
    states_data = {}
    if params[:country_id]
      states = CS.states(params[:country_id])
      states_data = states.to_a.map{ |state| [state[1], state[0].to_s]}
    end
    render json: {states: states_data}
  end


  def cities
    cities_data = {}
    if params[:state_id]
      cities = CS.cities(params[:state_id])
      cities_data = cities.map { |city| [city, city.downcase.split(' ').join('_')]}
    end
    render json: {cities: cities_data}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      flash[:notice] = find_error(@user)
      flash[:level] = 'ERROR'
      render :new
    end
  end


  def edit
  end


  def update
    if @user.update_attributes(user_params)
      flash[:notice] = 'User Updated successfully'
      flash[:level] = 'SUCCESS'
      redirect_to root_path
    end
  end


  def destroy
    @user.destroy
    flash[:notice] = 'User Deleted successfully'
    flash[:level] = 'SUCCESS'
    redirect_to root_path
  end


  private


  def find_user
    @user = User.find(params[:id])
  end


  def user_params
    params.require(:user).permit(:name, :address, :country, :city, :state)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'block-shadow-info menu_selected' : ''
    link_to link_text, link_path, class: class_name
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_graph.html.erb
<div id="map"></div>

app/views/home/_table.html.erb
<table class="table striped hovered cell-hovered border bordered" id="distance_from_place">
  <thead>
  <tr>
    <td class="sortable-column">Name</td>
    <td class="sortable-column">Address</td>
    <td class="sortable-column">Latitude</td>
    <td class="sortable-column">Longitude</td>
    <td class="sortable-column">Get Location</td>
    <td class="sortable-column">Select Source and Destination</td>
    <td class="sortable-column">Calculate Distance </td>
    <% if @user.present? %>
        <td class="sortable-column">Distance from <strong><%= @user.name %>'s</strong> Place</td>
    <% else %>
        <td class="sortable-column">Distance from Place</td>
    <% end %>
    <td class="sortable-column">Actions </td>
  </tr>
  </thead>

  <% unless @users.blank? %>
      <% @users.each do |user| %>
          <%
             image = (user.id == @user.id) ? 'distance_selected.png' : 'distance.png'
          %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.full_address %></td>
            <td><%= user.latitude %></td>
            <td><%= user.longitude %></td>

            <td style="text-align: center;">
              <%= link_to image_tag('location.png', height:35 ,width: 35), gmap_home_index_path(id: user.id), remote: true %>
            </td>
            <td><%= link_to 'Choose', '#', class: 'compare button bg-cyan button_shadow', rel: user.id %></td>

            <td><%= link_to image_tag(image, height:50 ,width: 80), distance_from_home_path(user), class: 'distance_from', remote: true %></td>
            <td><%= @user.distance_from([user.latitude, user.longitude]).round(2)%> miles</td>
            <td style="width: 100px;"><%= link_to image_tag('edit.png', height:30 ,width: 30), edit_user_path(user) %> <%= link_to image_tag('delete.png', height:30 ,width: 30), user_path(user), method: :delete, data: {confirm: 'Are you sure? This will not be recovered later.'} %></td>
          </tr>
      <% end %>
  <% end %>
</table>

<div data-role="dialog" id="dialog4" class="padding20" data-close-button="true" data-type="warning">
  <h1>Simple dialog</h1>
  <p>
    Dialog :: Metro UI CSS - The front-end framework for developing projects on the web in Windows Metro Style
  </p>
</div>

app/views/home/distance_from.js.erb
$('#distance_from_place').replaceWith("<%= escape_javascript(render(partial: 'table')) %>");

app/views/home/gmap.js.erb
showDialog('dialog7');
$('.graph_heading').text('Location');
$('.graph_para').text('<%= @user.full_address %>');
$('#map').replaceWith('<%= escape_javascript(render(partial: 'graph')) %>');
initMap(<%= "#{@user.latitude}, #{@user.longitude}" %>);

app/views/home/index.html.erb
<div id="table_detail">
  <%= render partial: 'table' %>
</div>

<br>
<div style="float: right;margin-right: 220px; margin-bottom: 15px;">
  <%= link_to 'Get Distance', '#' , id: 'distance', class: 'button bg-orange' %>
</div>
<br>


<div data-role="dialog" id="dialog7" class="padding20" data-close-button="true" data-windows-style="true">
  <div class="container">
    <h3 class="graph_heading"></h3>
    <p class="graph_para"></p>
    <div id="map-container">
      <div id="map-canvas">
        <%= render partial: 'graph' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GeoCodesDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="initial-scale=1.0">
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAohrcLOAWU0tTqLXpFKl5uCijA08j3RX8" async defer></script>
  <%= csrf_meta_tags %>
  <script type="text/javascript">
      var notifyMessage = '<%= flash[:notice] %>',
              notifyLevel = '<%= flash[:level] %>';
  </script>
</head>
<body>
<div class="container page-content">
  <h1><% link_to root_path, class: '"nav-button transform'  do %>
        <span></span>
    <% end %>&nbsp;Google Maps Demo</h1>
  <ul class="m-menu" >

    <li class="h-menu"> <%= nav_link 'Add Address', new_user_path %></li>
    <li class="h-menu"> <%= nav_link 'Map Activities', root_path %></li>
  </ul>

  <%= yield %>
</div>

</body>
</html>

app/views/users/_form.html.erb
<div class="grid">
  <%= form_for @user do |f| %>
      <div class="row cells2">
        <div class="cell">
          <label>Name</label>
          <div class="input-control text full-size">
            <%= f.text_field :name%>
          </div>
        </div>
        <div class="cell">
          <label>Country</label>
          <div class="input-control text full-size">
            <% country_list = CS.countries.to_a.map{ |a| [a[1], a[0].to_s]}%>
            <% if @user.new_record? %>
                <%= f.select :country,  country_list, {prompt: 'Select Country'}, { onchange: "getStates();"} %>
            <% else %>
                <%= f.select :country,  country_list, {selected: @user.country}, { onchange: "getStates();"} %>
            <% end %>

          </div>
        </div>
      </div>

      <div class="row cells2">
        <div class="cell">
          <label>State</label>
          <div class="input-control text full-size">
            <%= f.select :state, {},  {prompt: 'Select State'}, {onchange: "getCities();"} %>
          </div>
        </div>

        <div class="cell">
          <label>City</label>
          <div class="input-control text full-size">
            <%= f.select :city,  {}, {prompt: 'Select City'} %>
          </div>
        </div>
      </div>


      <div class="row cells2">
        <div class="cell">
          <label>Address</label>
          <div class="input-control text full-size">
            <%= f.text_field :address %>
          </div>
        </div>
        <div class="cell">
          <div class="input-control text full-size">
          </div>
        </div>
      </div>

      <%= f.submit class: 'button bg-orange' %>
  <% end %>
</div>

app/views/users/edit.html.erb
<br>
<div class="example" data-text="Edit User Details">
  <%= render partial: 'form' %>
</div>

<%= javascript_tag do %>
    <% unless @user.new_record? %>
        getSelectedStates('<%= @user.state_name %>');
        getSelectedCities('<%= @user.city_name %>', '<%= @user.state %>');
    <% end %>
<% end %>

app/views/users/new.html.erb
<br>
<div class="example" data-text="User Details">
  <%= render partial: 'form' %>
</div>